language: ruby
bundler_args: --without development
matrix:
  include:
    - rvm: 1.9.3
    - rvm: ruby-head
    - rvm: 2.0.0 
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.0.0
services:
  - mongodb
